reviewed the article, made some changes for consistency
thorbenheins/asyncapi-website pull request #1
Opened 2024-11-26 07:10 UTC by thorbenheins

maybe we should also update this to contain information about event hub?

2024-11-26 17:27 UTC, vlazw approved these changes
lgtm

2024-11-28 13:35 UTC, manuelottlik requested changes

2024-11-28 13:35 UTC, manuelottlik commented on config/casestudies/hdi.yml
> +  In an ideal world, the configuration would be an AsyncAPI document instead of a custom configuration, yet as a first step we want to establish AsyncAPI as documentation
Ich weiß noch nicht, ob ich das so unterschreiben würde – IDLs auch als Infrastrukturkonfiguration zu nutzen hat mMn auch Nachteile. Das würde ich also so erstmal nicht in die Case Study schreiben.

2024-11-28 13:35 UTC, manuelottlik commented on config/casestudies/hdi.yml
> +  This approach makes our asynchronous communication as transparent and discoverable as our synchronous communication.
Hier könnte dann auch ein Outlook hin, der auf ein Internal Developer Portal hinweist, in dem ein Katalog existiert.

2024-11-28 13:35 UTC, manuelottlik commented on config/casestudies/hdi.yml
> +    - (Outlook) Replace the custom configuration model and use AsyncAPI documents to configure asynchronous communication instead.
siehe erster Kommentar

2024-11-29 07:09 UTC, thorbenheins commented on config/casestudies/hdi.yml
> +  This approach makes our asynchronous communication as transparent and discoverable as our synchronous communication.
Habe ich mit in den Outlook reingepackt.

2024-11-29 07:10 UTC, thorbenheins commented on config/casestudies/hdi.yml
> +  In an ideal world, the configuration would be an AsyncAPI document instead of a custom configuration, yet as a first step we want to establish AsyncAPI as documentation
hab ich hier raus genommen..

2024-11-29 07:10 UTC, thorbenheins commented on config/casestudies/hdi.yml
> +    - (Outlook) Replace the custom configuration model and use AsyncAPI documents to configure asynchronous communication instead.
... und hier als "evaluate possibility" mit rein genommen. Passt das dann so?

2024-11-29 11:34 UTC, manuelottlik approved these changes
lgtm

2024-11-29 11:59 UTC, merged